# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WEBLI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


pod "SCPageViewController"

  # Pods for WEBLI

  target 'WEBLITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WEBLIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
